### ISSUE TITLE
Endless loop when failing to connect to RT

### ISSUE THREAD

**Issue by hmpf** [Uninett/argus_ticket_rt#4]
```
2022-12-09 13:41:57,459 rt_client.v2.client DEBUG    RT Client Authentication Failure
2022-12-09 13:41:57,459 argus_ticket_rt ERROR    Request Tracker: Client could not be created.
Traceback (most recent call last):
  File "foo/.virtualenvs/argus/lib/python3.10/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "foo/.virtualenvs/argus/lib/python3.10/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "foo/.virtualenvs/argus/lib/python3.10/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "foo/.virtualenvs/argus/lib/python3.10/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "foo/.virtualenvs/argus/lib/python3.10/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "foo/.virtualenvs/argus/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "foo/.virtualenvs/argus/lib/python3.10/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "foo/.virtualenvs/argus/lib/python3.10/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fc251d04ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "foo/.virtualenvs/argus/lib/python3.10/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "foo/.virtualenvs/argus/lib/python3.10/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "foo/.virtualenvs/argus/lib/python3.10/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='rt.example.com', port=443): Max retries exceeded with url: /NoAuth/Login.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc251d04ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "foo/.virtualenvs/argus/lib/python3.10/site-packages/argus_ticket_rt.py", line 53, in create_client
    client = Client(
  File "foo/.virtualenvs/argus/lib/python3.10/site-packages/rt_client/client.py", line 23, in Client
    return _CLIENTS[str(version).lower()](*args, **kwargs)
  File "foo/.virtualenvs/argus/lib/python3.10/site-packages/rt_client/v2/client.py", line 65, in __init__
    self.authenticate()
  File "foo/.virtualenvs/argus/lib/python3.10/site-packages/rt_client/v2/client.py", line 80, in authenticate
    self.sess.post(
  File "foo/.virtualenvs/argus/lib/python3.10/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "foo/.virtualenvs/argus/lib/python3.10/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "foo/.virtualenvs/argus/lib/python3.10/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "foo/.virtualenvs/argus/lib/python3.10/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='rt.example.com', port=443): Max retries exceeded with url: /NoAuth/Login.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc251d04ac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

```

**Comment by hmpf** [comment]
This can probably be tested for by setting TICKET_ENDPOINT to a non-existing domain.

**Comment by johannaengland** [comment]
Notes from a meeting with @hmpf:
The problem here is that trying to connect the RT client to a non-existing domain (or simply when not connected to the internet) leads to a login-loop.

We need to deal with that by setting a timeout every time we are interacting with the library and then tell the frontend at which point something went wrong.

**Comment by johannaengland** [comment]
Before continuing to work on this issue we need to figure out if the merging of #6 and #9 will already fix this issue.

**Comment by hmpf** [comment]
With the new rt client used via frontend I observe:

- 404 for https://example.com
- 405 after a loong while for a more complete domain that does not host RT
- Sometimes no error at all, just nothing happening
- Bizarre things if I turn off the external net completely (I test against a database on localhost, so turning off the external net shouldn't affect things)

I will close this issue, but I suspect a procedure is needed (with standardized hosts) to test for such problems
